# -*- coding: utf-8 -*-
"""todo-cli-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBCOSOK6nF1ikFqNvjeLYKJR6hfRYvds
"""

import os

FILENAME = "tasks.txt"

def load_tasks():
    if not os.path.exists(FILENAME):
        return []
    with open(FILENAME, "r") as file:
        return [line.strip() for line in file.readlines()]

def save_tasks(tasks):
    with open(FILENAME, "w") as file:
        for task in tasks:
            file.write(task + "\n")

def show_tasks(tasks):
    if not tasks:
        print("📭 Görev bulunmuyor.")
    else:
        print("\n📋 GÖREV LİSTESİ:")
        for i, task in enumerate(tasks, start=1):
            print(f"{i}. {task}")
        print()

def main():
    tasks = load_tasks()

    while True:
        print("\n[1] Görev Ekle  [2] Görevleri Göster  [3] Sil  [4] Çıkış")
        choice = input("Seçiminiz: ")

        if choice == "1":
            task = input("Yeni görev: ")
            tasks.append(task)
            save_tasks(tasks)
            print("✅ Görev eklendi.")
        elif choice == "2":
            show_tasks(tasks)
        elif choice == "3":
            show_tasks(tasks)
            try:
                index = int(input("Silmek istediğiniz görev numarası: ")) - 1
                if 0 <= index < len(tasks):
                    deleted = tasks.pop(index)
                    save_tasks(tasks)
                    print(f"🗑️ '{deleted}' silindi.")
                else:
                    print("❗Geçersiz görev numarası.")
            except ValueError:
                print("❗Lütfen sayı girin.")
        elif choice == "4":
            print("👋 Görüşmek üzere!")
            break
        else:
            print("❗Geçersiz seçim.")

if __name__ == "__main__":
    main()